### ISSUE TITLE
Fix back button behavior when selecting graph type

### ISSUE THREAD

**Issue by nikolas** [ccnmtl/econplayground.js#1365]
Clicking a graph type in the graph picker should navigate to a new URL with pushState so the back button works here.

**Comment by Evan-CTL** [comment]
Refresh, also doesn't preserve the page state. After selecting a graph hitting refresh will drop the user back into the original card display.

**Comment by Evan-CTL** [comment]
It might also help navigation to extend the breadcrumbs into individual graph views. That could be a cleaner replacement to the inner Back button in-page.

**Comment by nikolas** [comment]
We've implemented well-behaving react links in Mediathread when switching between item detail view and collection view - You can see how this is put together here: https://github.com/ccnmtl/mediathread/blob/master/media/js/src/CollectionTab.jsx#L103
