### ISSUE TITLE
Resolve deprecated react-sticky problem

### ISSUE THREAD

**Issue by nikolas** [ccnmtl/econplayground.js#819]
react-sticky is causing a deprecation error:

> Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.

See: https://github.com/captivationsoftware/react-sticky/pull/292#issuecomment-565818709

We either patch react-sticky ourselves, take over maintenance, or switch to another method of achieving this. I implemented this in Mediathread using just `position: sticky;` CSS.

**Comment by nbuonin** [comment]
Resolved by #879
